name: Default

on:
  pull_request:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: nixbuild/nix-quick-install-action@v27
        with: { load_nixConfig: false }
      - name: Build
        run: nix develop -c dune build
      - name: Run quick tests
        run: ./_build/default/tests/unit/unit_tests.exe -q
